name: pt
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - jupyterlab
  - matplotlib
  - pandas
  - scipy
  - pip:
    - pyro-ppl==1.3.0

