name: pyro
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.8.0
  - jupyterlab
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - scikit-learn
  - pip
  - pip:
    - pyro-ppl==1.4.0
    - git+https://github.com/jafetgado/resreg.git